const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8082',{waitUntil:'networkidle'});
 await page.screenshot({path:'/tmp/robot3-desktop.png',fullPage:true});
 const map=await page.locator('.map-panel').boundingBox(),host=await page.locator('.host-console').boundingBox();
 assert(map.x+map.width<=host.x,'Simulation is left of Host GUI');assert(map.width>host.width*2,'Simulation occupies the larger area');
 for(const id of ['quantity','start','total','transport','remaining','completed'])assert(await page.locator('.host-console #'+id).count()===1,`Host GUI contains ${id}`);
 assert.equal(await page.locator('#total').textContent(),'—');
 await page.click('#start');await page.click('#play');
 assert.equal(await page.locator('#total').textContent(),'2');
 await page.locator('#timeline').evaluate(el=>{el.value=RobotSimulation.makePlan(2).jobs[0].dispatch;el.dispatchEvent(new Event('input'));});
 assert.equal(await page.locator('#transport').textContent(),'1');
 await page.locator('#timeline').evaluate(el=>{el.value=RobotSimulation.makePlan(2).jobs[1].dispatch;el.dispatchEvent(new Event('input'));});
 assert.equal(await page.locator('#transport').textContent(),'0');assert.equal(await page.locator('#remaining').textContent(),'1');
 await page.screenshot({path:'/tmp/robot3-running.png',fullPage:true});
 await page.locator('#timeline').evaluate(el=>{el.value=el.max;el.dispatchEvent(new Event('input'));});
 assert.equal(await page.locator('#run-status').textContent(),'주문 완료');assert.equal(await page.locator('#completed').textContent(),'2');
 await page.click('#reset');await page.fill('#quantity','3');await page.click('#start');await page.click('#play');
 assert.equal(await page.locator('#transport').textContent(),'3');
 await page.click('#next');await page.click('#previous');
 await page.locator('#timeline').evaluate(el=>{el.value=el.max;el.dispatchEvent(new Event('input'));});
 assert.equal(await page.locator('#completed').textContent(),'3');
 await page.click('#open-details');
 const download=page.waitForEvent('download');await page.click('#export');assert.equal((await download).suggestedFilename(),'robot3-simulation-log.json');
 await page.click('#close-details');
 await page.click('[data-tab=gallery]');assert.equal(await page.locator('.gallery-card').count(),9);await page.locator('.gallery-card').first().click();assert(await page.locator('#photo-dialog').isVisible());await page.keyboard.press('Escape');
 const allImages=await page.locator('img').evaluateAll(imgs=>imgs.every(i=>i.complete&&i.naturalWidth>0));assert(allImages,'All 9 photos should load');
 await page.click('[data-tab=simulation]');await page.click('#reset');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/robot3-mobile.png',fullPage:true});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No horizontal overflow on mobile');
 assert.deepEqual(errors,[]);
 await browser.close();console.log('PASS: desktop/mobile, order input, counters, seek, 3-item order, photos, modal, export, no browser errors.');
})().catch(e=>{console.error(e);process.exit(1)});
