const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const els=new Map();
const el=id=>{if(!els.has(id))els.set(id,{textContent:'',hidden:false,disabled:false,checked:false,click(){return this.onclick();}});return els.get(id);};
let seq=0,interval,fail=false,changes=0;
let state={status:'idle',quantity:0,order_id:null,command:null,acked_seq:0,time:0,log:[],auto:false};
const requests=[];
const sandbox={window:{},document:{getElementById:el},location:{hostname:'127.0.0.1',protocol:'http:',search:''},sessionStorage:{getItem(){throw Error('blocked');},setItem(){throw Error('blocked');}},crypto:{randomUUID:()=>`test-uuid-${++seq}`},URLSearchParams,AbortController,setTimeout,clearTimeout,setInterval:f=>interval=f};
sandbox.fetch=async(url,opts)=>{
 if(fail)throw Error('network unavailable');
 const a=url.split('/').at(-1),d=JSON.parse(opts.body);requests.push(a);
 if(a==='start')state={...state,status:'running',quantity:d.quantity,order_id:'order1',command:{order_id:'order1',seq:1,target_time:0}};
 if(a==='auto')state={...state,auto:d.enabled};
 if(a==='next')state={...state,status:'running',command:{order_id:'order1',seq:2,target_time:3}};
 if(a==='ack')state={...state,status:'waiting',command:null,acked_seq:1};
 if(a==='pause')state={...state,status:'paused'};
 if(a==='disconnect')state={...state,status:'idle',quantity:0,command:null};
 return {ok:true,json:async()=>structuredClone(state)};
};
vm.runInNewContext(fs.readFileSync('host-client.js','utf8'),sandbox);
const b=sandbox.window.HostBridge;
const flush=()=>new Promise(r=>setImmediate(r));
(async()=>{
 b.init(()=>changes++);
 el('host-connect').click();await flush();
 assert.equal(b.online,true);
 await b.start(2);assert.equal(b.state.status,'running');
 b.complete();b.complete();await flush();
 assert.equal(requests.filter(a=>a==='ack').length,1);
 assert.equal(b.state.status,'waiting');
 state={...state,status:'running',command:{order_id:'order1',seq:2,target_time:3}};
 fail=true;await interval();assert.equal(b.online,false);
 fail=false;await interval();assert.equal(b.state.status,'paused');
 assert.equal(requests.at(-1),'pause');assert.equal(b.online,true);
 el('host-connect').click();await flush();assert.equal(b.enabled,false);
 await el('host-connect').click();await flush();
 state={...state,status:'idle',auto:true};b.state=structuredClone(state);
 const before=requests.length;
 await Promise.all([b.step(2),b.step(2)]);
 assert.deepEqual(requests.slice(before),['auto','start']);assert.equal(b.state.auto,false);
 state={...state,status:'waiting'};b.state=structuredClone(state);
 await b.step(2);assert.equal(requests.at(-1),'next');assert.equal(b.state.status,'running');
 state={...state,status:'waiting'};b.state=structuredClone(state);fail=true;
 const failed=requests.length;await b.step(2);assert.equal(requests.length,failed);
 assert.ok(changes>=5);
 console.log('PASS: client storage fallback, connection, ACK coalescing, connection loss, explicit recovery hold and disconnect.');
})().catch(e=>{console.error(e);process.exitCode=1;});
